language: cpp
cache:
  pip: true
  directories:
env:
  global:
    - P4FPGA=$PWD
script:
- cd $P4FPGA; ./bootstrap_env.sh; ./bootstrap.sh; cd build; make -j4
sudo: required
dist: trusty
os:
- linux
notifications:
  email: false
